lr: 0.001
weight_decay: 0
milestones: [100]
clip_grad: 0
max_epochs: 1000
early_stop: 50

model_args:
  input_classes_list: [6, 3, 43, 44, 64, 2506]
  embedding_dim: 64
  output_dim: 11
  hidden_dim: 128
